# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-21 20:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social_twitter', '0002_added_sentimet_and_percent_to_tweet'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tweet',
            old_name='percentage',
            new_name='score',
        ),
    ]
